trigger:
- main

parameters:
- name: vargroup
  displayName: DevOps variable group
  type: string
  default: "wofs-pipeline-variables" 
- name: package_version
  displayName: Package Version
  type: string
  default: 1.1

variables:
- group: ${{ parameters.vargroup }}
- name: PACKAGE_VERSION
  value: ${{ parameters.package_version }}.$(Build.BuildId)

stages:
- stage: Build
  displayName: Build Package
  jobs:
      - job:
        displayName: $(DEFAULT_POOL_IMAGE)
        pool:
          vmImage: $(DEFAULT_POOL_IMAGE)
        strategy:
          matrix:
            Python38:
              python.version: '3.8'              
              env_file: 'environment_py38.yml'
            Python310:
              python.version: '3.10'              
              env_file: 'environment_py310.yml'
              
        steps:
        - bash: echo "##vso[task.prependpath]$CONDA/bin"
          displayName: Add conda to PATH
      
        # Install mamba to manage dependencies faster
        - bash: |
            conda config --set allow_conda_downgrades true
            conda install conda=23.11.0 -y
            conda config --set solver libmamba
          displayName: Install Mamba package manager
     
        - task: PipAuthenticate@1
          displayName: 'Pip Authenticate'
          inputs:
            artifactFeeds: 'Warn-on-Forecast/wofs-post'
            
        - bash: |
            # workaround based on recent failures
            rm /usr/share/miniconda/pkgs/cache/*.json    
            conda env create --file $(env_file)
          displayName: Create mamba environment            
     
        - bash: |
            source activate wofs-func
            python setup.py bdist_wheel
          displayName: Build wheel

        - script: 'pip install twine keyring artifacts-keyring'
          displayName: Install publishing prerequisites
  
        - task: TwineAuthenticate@1
          inputs:
            artifactFeed: 'Warn-on-Forecast/wofs-post'
          displayName: Authenticate Twine

        - script: |
            python -m twine upload -r wofs-post --config-file $(PYPIRC_PATH) --skip-existing dist/*.whl
          displayName: Publish Package

        - task: GithubRelease@1 
          displayName: 'Create GitHub Release'
          condition: eq(variables['AZ_DEVOPS_DEPLOY_GITHUB'], 'TRUE')
          inputs:
            gitHubConnection: WarnOnForecast-Github
            repositoryName: NOAA-National-Severe-Storms-Laboratory/frdd-wofs-ml-w2w
            isPreRelease: false
            tagSource: userSpecifiedTag
            assets: dist/*.whl
            tag: $(PACKAGE_VERSION)-py$(python.version)
