name: wofs-func
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.15
  - pip=23.3.2
  - scikit-image>=0.19
  - xarray=0.21.1
  - pandas>=1.3.0
  - scikit-learn=1.0.2
  - scikit-learn-intelex=2023.0.1
  - importlib_resources=6.0.0
  - numpy=1.22.4
  - pip:
    - imblearn
    - hyperopt
    - lightgbm
