name: wofs-func
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.2
  - scikit-image>=0.19
  - xarray>=0.18  
  - pandas>=1.3.0
  - scikit-learn=1.0.2
  - scikit-learn-intelex=2023.0.1
  - pip:
    - importlib_resources==6.4.5
    - importlib_metadata==7.2.1  
    - imblearn
    - hyperopt
    - lightgbm
